export const ADD_MODAL_DATA: 'ADD_MODAL_DATA' = 'ADD_MODAL_DATA';
export const DELETE_MODAL_DATA: 'DELETE_MODAL_DATA' = 'DELETE_MODAL_DATA';
export const ADD_MODAL_PROFILE: 'ADD_MODAL_PROFILE' = 'ADD_MODAL_PROFILE';
