export const ADD_INGREDIENT_BURGERCONSTRUCTOR: "ADD_INGREDIENT_BURGERCONSTRUCTOR" =
  "ADD_INGREDIENT_BURGERCONSTRUCTOR";
export const DELETE_INGREDIENT_BURGERCONSTRUCTOR: "DELETE_INGREDIENT_BURGERCONSTRUCTOR" =
  "DELETE_INGREDIENT_BURGERCONSTRUCTOR";
export const CHANGE_ORDER_BURGERCONSTRUCTOR: "CHANGE_ORDER_BURGERCONSTRUCTOR" = "CHANGE_ORDER_BURGERCONSTRUCTOR";
export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const GET_ORDER_CLOSE: "GET_ORDER_CLOSE" = "GET_ORDER_CLOSE";