export const GET_ORDERLIST_REQUEST: "GET_ORDERLIST_REQUEST" = "GET_ORDERLIST_REQUEST";
export const GET_ORDERLIST_SUCCESS: "GET_ORDERLIST_SUCCESS" = "GET_ORDERLIST_SUCCESS";
export const GET_ORDERLIST_FAILED: "GET_ORDERLIST_FAILED" = "GET_ORDERLIST_FAILED";