export const GET_PROFILE_ORDERLIST_REQUEST: "GET_PROFILE_ORDERLIST_REQUEST" = "GET_PROFILE_ORDERLIST_REQUEST";
export const GET_PROFILE_ORDERLIST_SUCCESS: "GET_PROFILE_ORDERLIST_SUCCESS" = "GET_PROFILE_ORDERLIST_SUCCESS";
export const GET_PROFILE_ORDERLIST_FAILED: "GET_PROFILE_ORDERLIST_FAILED" = "GET_PROFILE_ORDERLIST_FAILED";